force-app/main/default/objects/Website_Home_Page__c/Website_Home_Page__c.object-meta.xml
<CustomObject>
    <label>Website_Home_Page</label>
    <nameField>
        <label>Website_Home_Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Website_Home_Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Website_Home_Page__c/fields/Home_Page_HTML_Text__c.field-meta.xml
<CustomField>
    <fullName>Home_Page_HTML_Text__c</fullName>
    <label>Home_Page_HTML_Text</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Website_Home_Page__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Website_Home_PageSearchController.cls
public with sharing class Website_Home_PageSearchController {
    public Website_Home_PageSearchController() {

    }
    @AuraEnabled
    public static List<Website_Home_Page__c> searchWebsite_Home_Page( String searchTerm ) {
        List<Website_Home_Page__c> accounts = new List<Website_Home_Page__c>();
        if ( String.isNotBlank( searchTerm ) ) {
            List<List<SObject>> searchResults = [
                FIND :searchTerm
                RETURNING Website_Home_Page__c(
                    Home_Page_HTML_Text__c, Name__c
                    ORDER BY Name__c
                    LIMIT 10
                )
            ];
            accounts = searchResults[0];
        }
        return accounts;
    }
}